EmployeeTable/EmployeeTable/Controllers/CreateController.cs
using EmployeeTable.Context;
using EmployeeTable.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmployeeTable.Controllers
{
    public class CreateController : Controller
    {
        // GET: Create
        /*
         * Контроллер создания новой записи об отсутствии
         */
        public ActionResult Index()
        {
            var model = new Absence();
            model.Date = DateTime.Now;
            return View(model);
        }
    }
}

EmployeeTable/EmployeeTable/Controllers/EmployeesController.cs
using EmployeeTable.Context;
using EmployeeTable.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmployeeTable.Controllers
{
    public class EmployeesController : Controller
    {
        AbsencesContext db = new AbsencesContext();

        // GET: Employees

        /*
         * Контроллер сотрудники
         */

        public ActionResult Index(int? id)
        {
            var employee  = db.Employees.Where(x => x.IdEmployee == id);
            return View(employee);
        }
    }
}

EmployeeTable/EmployeeTable/Controllers/NewempController.cs
using EmployeeTable.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmployeeTable.Controllers
{
    public class NewempController : Controller
    {
        // GET: Newemp
        public ActionResult Index()
        {
            var model = new Employee();
            return View(model);
        }
    }
}

EmployeeTable/EmployeeTable/Views/Layout/_Layout.cshtml
@*Подложка всех страниц*@

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Табель</title>
    @*Подключаем css и jquery. Необходимо для работы со стилями и некоторыми пользовательскими элементами*@
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/themes/base/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery-ui-timepicker-addon")

    @*<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
        <script language="javascript" type="text/javascript" src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
        <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>*@
    @*Отображение календаря для ввода даты, что упрощает ввод*@
    <script>
        $().ready(function () {

            $('.datePicker').datetimepicker({
                dateFormat: 'd.m.yy'
            });
        })
    </script>

    
</head>
<body>
    <br />
    
     <h2>Табель отсутствия на работе сотрудников</h2>
    <table>@*Верхняя панель с основными ссылками на страницы*@
        <tr>
            <td>
                @Html.ActionLink("Главная страница", "Index", "Home",new { @class = "MainPage"})
            </td>
            <td>
                @Html.ActionLink("Запись об отсутствии", "Create", null, new { @class = "Add" })
            </td>
            <td>
                @Html.ActionLink("Список сотрудников", "Employees", null, new { @class = "EmployeeList" })
            </td>
            <td>
                @Html.ActionLink("Добавить сотрудника", "Newemp", null, new { @class = "EmployeeAdd" })
            </td>
        </tr>
    </table>
    <br />

    @*Отображение содержимого страницы*@
    @RenderBody()
</body>
</html>