EmployeeTable/EmployeeTable/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EmployeeTable.Models
{
    public class Employee
    {
        /*
         Класс - сотрудник
         */
         /// <summary>
         /// id Сотрудника
         /// </summary>
        [Key]public int IdEmployee { get; set; }
        /// <summary>
        /// Фамилия
        /// </summary>
        [Required, Display(Name = "Фамилия")]
        public string Surname { get; set; }
        /// <summary>
        /// Имя
        /// </summary>
        [Required, Display(Name = "Имя")]
        public string Name { get; set; }
        /// <summary>
        /// Отчёство
        /// </summary>
        [Required, Display(Name = "Отчество")]
        public string Lastname { get; set; }
        /// <summary>
        /// Фамилия и инициалы
        /// </summary>
        [Required, Display(Name = "ФИО")]
        public string Fullname { get; set; }

        /// <summary>
        /// id Должности
        /// </summary>
        public int idPosition { get; set; }
        public Position Position { get; set; }

        public ICollection<Absence> Absences { get; set; }

        public Employee()
        {
            Absences = new List<Absence>();
        }
    }
}

EmployeeTable/EmployeeTable/Controllers/CreateController.cs
using EmployeeTable.Context;
using EmployeeTable.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmployeeTable.Controllers
{
    public class CreateController : Controller
    {
        // GET: Create
        /*
         * Контроллер создания новой записи об отсутствии
         */
        public ActionResult Index()
        {
            var model = new Absence();
            model.Date = DateTime.Now;
            return View(model);
        }
    }
}

EmployeeTable/EmployeeTable/Controllers/DelempController.cs
using EmployeeTable.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmployeeTable.Controllers
{
    public class DelempController : Controller
    {
        AbsencesContext db = new AbsencesContext();

        // GET: Delemp
        /*
         * Контроллер удаления сотрудника
         */

        public ActionResult Index(int id)
        {
            var employees = db.Employees.Where(x => x.IdEmployee == id);
            return View(employees);
        }
    }
}

EmployeeTable/EmployeeTable/Controllers/DeleteController.cs
using EmployeeTable.Context;
using EmployeeTable.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmployeeTable.Controllers
{
    public class DeleteController : Controller
    {
        AbsencesContext db = new AbsencesContext();

        // GET: DeleteConfirmed

            /*
             * Контроллер удаления записи об отсутствии
             */

        public ActionResult Index(int id)
        {
            var absences = db.Absences.Where(x => x.IdAbsences == id);
            return View(absences);
        }
    }
}

EmployeeTable/EmployeeTable/Controllers/EmployeesController.cs
using EmployeeTable.Context;
using EmployeeTable.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmployeeTable.Controllers
{
    public class EmployeesController : Controller
    {
        AbsencesContext db = new AbsencesContext();

        // GET: Employees

        /*
         * Контроллер сотрудники
         */

        public ActionResult Index(int? id)
        {
            var employee  = db.Employees.Where(x => x.IdEmployee == id);
            return View(employee);
        }
    }
}

EmployeeTable/EmployeeTable/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Web.UI.WebControls;
using EmployeeTable.Context;
using System.Threading.Tasks;
using EmployeeTable.Models;
using System.Data.Entity.Migrations;

namespace EmployeeTable.Contollers
{
    public class HomeController : Controller
    {
        /*
         * Контроллер домашней страницы (страница отсутствий)
         */


        AbsencesContext db = new AbsencesContext();

        //public ActionResult Index()
        //{

        //    var absences = db.Absences.Include(f => f.Employee);

        //    return View(absences.ToList());
        //}

        /// <summary>
        /// Обрабатывает GET запрос Index и формирует список отсутствий сотрудников, включая фильтры
        /// </summary>
        /// <param name="Fullname"></param>
        /// <param name="Name"></param>
        /// <param name="Reason"></param>
        /// <returns></returns>
        public ActionResult Index(string Fullname, string Name, string Reason)
        {
            //Основная выборка отсутствий с сотрудниками
            IQueryable<Absence> absences = db.Absences.Include(p => p.Employee);

            //В одном (или нескольких) if отфильтровываем записи
            if (!String.IsNullOrEmpty(Fullname) && Fullname != "Все")
            {
                absences = absences.Where(p => p.Employee.Fullname == Fullname).OrderBy(x => x.Date);
            }

            if (!String.IsNullOrEmpty(Name) && Name != "Все")
            {
                absences = absences.Where(p => p.Employee.Position.Name == Name).OrderBy(x => x.Date);
            }

            if (!String.IsNullOrEmpty(Reason) && Reason != "Все")
            {
                absences = absences.Where(p => p.Reason == Reason).OrderBy(x=>x.Date);
            }

            //Заполняем дропбоксы с фильтрами значениями из таблиц
            List<Employee> employees = db.Employees.ToList();
            employees.Insert(0, new Employee { Fullname = "Все", IdEmployee = 0 });

            List<Position> positions = db.Positions.ToList();
            positions.Insert(0, new Position {  Name = "Все", IdPosition = 0 });

            List<Absence> absenceslist = db.Absences.ToList();
            absenceslist.Insert(0, new Absence { IdAbsences = 0, idEmployee = 0, Reason = "Все" });

            //Создаём и заполняем модель данных
            AbsenceListViewModel alvm = new AbsenceListViewModel
            {
                Absences = absences.ToList(),
                Fullnames = new SelectList(employees, "Fullname", "Fullname"),
                Names = new SelectList(positions, "Name", "Name"),
                Reason = new SelectList(absenceslist, "Reason", "Reason")
            };
            return View(alvm);
        }

        /// <summary>
        /// Сотрудники включая должности
        /// </summary>
        /// <returns></returns>
        public ActionResult Employees()
        {
            IQueryable<Employee> employees = db.Employees.Include(p=>p.Position);
            return View(employees);
        }

        /// <summary>
        /// Создание записи об отсутствии (GET)
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Create()
        {
            //Заполняем дропбокс с ФИО сотрудников
            SelectList Fullnames = new SelectList(db.Employees, "idEmployee", "Fullname");
            ViewBag.Employees = Fullnames;

            return View();
        }
        /// <summary>
        /// (POST) Возвращение данных о сотруднике и добавление в БД, включая проверку данных
        /// </summary>
        /// <param name="absence"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create([Bind(Include = "idEmployee,Date,Reason")]Absence absence)
        {
            //Если данные верны, то
            if (ModelState.IsValid)
            {
                //Добавляем запись об отсутствии
                db.Absences.Add(absence);
                //Применяем изменения к ЬД
                db.SaveChanges();
                //Возвращаемся на главную страницу (страницу отсутствий)
                return RedirectToAction("Index");
            }

            //Если не получилось, то снова заполняем дропбокс с сотрудниками 
            SelectList Fullnames = new SelectList(db.Employees, "idEmployee", "Fullname");
            ViewBag.Employees = Fullnames;

            //И идём обратно к заполнению данных для ввода и отображаем ошибки
            ViewBag.Message = "Некорректный ввод данных";
            return RedirectToAction("Employee");
        }

        /// <summary>
        /// Удаление записи об отсутствии, принимает id записи для поиска её в БЖ
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Delete(int id)
        {
            //Ищем запись в БД
            Absence absence = db.Absences.Find(id);
            if (absence == null)
            {   
                //Не нашли :(
                return HttpNotFound();
            }
            //Иначе возвращаем её в представление
            return View(absence);
        }
        /// <summary>
        /// Удаление записи об обсутствии, после нажатия "Удалить". Принимает id записи
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            //Cнова ищем эту запись (вдруг она уже удалилась)
            Absence absence = db.Absences.Find(id);
            if (absence == null)
            {
                //Не нашли :(
                return HttpNotFound();
            }
            //Удаляем запись 
            db.Absences.Remove(absence);
            //Применяем изменения к БД
            db.SaveChanges();
            //Возвращаемся на основную страницу
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Добавлние нового сотрудника
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Newemp()
        {
            return View();
        }
        /// <summary>
        /// Данные для добавления нового сотрудника
        /// </summary>
        /// <param name="employee"></param>
        /// <returns></returns>
        [HttpPost, ActionName("Newemp")]
        public ActionResult Newemp(Employee employee)
        {
            /*
             * Model.IsValid ругалась на отсутствующий Fullname поэтому здесь валидация происходит "вручную" (может можно как то лучше)
             * Если все поля (кроме ФИО) заполнены, то заполняем ФИО используя фамилию и первые буквы от имени и фамилии
             */
            if (employee.Surname != null && employee.Name != null &&
                employee.Lastname != null && employee.Position != null)
            {
                employee.Fullname = employee.Surname + " " +
                                    employee.Name.Substring(0, 1) + "." +
                                    employee.Lastname.Substring(0, 1) + ".";

                //Добавляем запись 
                db.Employees.Add(employee);
                //Применяем изменения в БД
                db.SaveChanges();
                //Показываем таблицу с добавленным сотрудником
                return RedirectToAction("Employees");
            }
            //Иначе возвращемся к странице ввода данных о новом сотруднике
            return View(employee);
        }

        /// <summary>
        /// Удаление сотрудника, принимает id сотрудника
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Delemp(int id)
        {
            //Сотрудник + должности, ищем сотрудника по id
            Employee employee = db.Employees.Include(p => p.Position).FirstOrDefault(x => x.IdEmployee == id);
            if (employee == null)
            {
                //Нету сотрудника :(
                return HttpNotFound();
            }
            //Возвращаем данные о сотруднике в представление
            return View(employee);
        }
        /// <summary>
        /// Данные для удаления сотрудника после ввода, принимает  id сотрудника
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost, ActionName("Delemp")]
        public ActionResult DelempConfirmed(int id)
        {
            //Сотрудник + должности, ищем сотрудника по id
            Employee employee = db.Employees.Include(p=>p.Position).FirstOrDefault(x=>x.IdEmployee ==id);
            if (employee == null)
            {
                //Нету сотрудника :(
                return HttpNotFound();
            }
            //Удаляем
            db.Employees.Remove(employee);
            //Применяем изменения
            db.SaveChanges();
            //Отображаем страницу с сотрудниками
            return RedirectToAction("Employees");
        }

        /// <summary>
        /// Изменение данных об отсутствии, принимает id записи
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Modify(int? id)
        {
            //Заполняем дропбокс с ФИО сотрудников
            SelectList Fullnames = new SelectList(db.Employees, "idEmployee", "Fullname");
            ViewBag.Employees = Fullnames;
            if (id == null)
            {
                //Нет такой записи :(
                return HttpNotFound();
            }

            //Ищем запись по id
            Absence absence = db.Absences.Find(id);
            if (absence != null)
            {
                //Если запись нашли, возвращаем в представление
                return View(absence);
            }
            //Иначе говорим что не нашли

EmployeeTable/EmployeeTable/Controllers/ModifyController.cs
using EmployeeTable.Context;
using EmployeeTable.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmployeeTable.Controllers
{
    public class ModifyController : Controller
    {
        AbsencesContext db = new AbsencesContext();

        // GET: Modify
        public ActionResult Index(int id)
        {
            var absences = db.Absences.Where(x => x.IdAbsences == id);
            return View(absences);
        }
    }
}

EmployeeTable/EmployeeTable/Controllers/ModifyEmpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmployeeTable.Controllers
{
    public class ModifyEmpController : Controller
    {
        // GET: ModifyEmp
        public ActionResult Index()
        {
            return RedirectToRoute("Home", "Index");
        }
    }
}

EmployeeTable/EmployeeTable/Controllers/NewempController.cs
using EmployeeTable.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmployeeTable.Controllers
{
    public class NewempController : Controller
    {
        // GET: Newemp
        public ActionResult Index()
        {
            var model = new Employee();
            return View(model);
        }
    }
}

EmployeeTable/EmployeeTable/Views/Home/Create.cshtml
@model EmployeeTable.Models.Absence
@{
    Layout = "~/Views/Layout/_Layout.cshtml";
}


<h3>Добавление записи об отсутствии</h3>
@**
На данной странице производится добавление новой записи в базу данных об отсутствии сотрудника

    LabelFor - отображение обозначения (названия) поля для воода
    DropDownListFor - выпадающий список
    EditorFor - поле для ввода текста
    ValidationMessageFor - проверка корректности ввода со стороны пользователя (отображает ошибку)
*@

@using (Html.BeginForm())
{
<table>
    <tr >
        <td width="20%">
            @Html.LabelFor(model => model.Employee.Fullname, "ФИО сотрудника")
        </td>
        <td width="40%" align="left"> @*Выбираем сотрудника из списка уже существующих*@
            @Html.DropDownListFor(model => model.idEmployee, ViewBag.Employees as SelectList)
        </td >
        <td width="40%">
        </td>
    </tr>
    <tr>
        <td >@*Ввод даты отсутствия (и времени) при помощи календаря*@
            @Html.LabelFor(model => model.Date, "Дата")
        </td>
        <td align="left">
            @Html.EditorFor(model => model.Date, "{0:dd.MM.yyyy hh:mm}", new { @class = "form-control default-date-picker" })
        </td>
        <td>
            @Html.ValidationMessageFor(model => Model.Date)
        </td>
    </tr>
    <tr>
        <td>@*Текст причины отсутствия работника*@
            @Html.LabelFor(model => model.Reason, "Причина")
        </td>
        <td align="left">
            @Html.EditorFor(model => model.Reason)
        </td>
        <td>
            @Html.ValidationMessageFor(model => Model.Reason)
        </td>
    </tr>
    <tr>
        <td colspan="3">@*Кнопка добавления*@
            <input type="submit" value="Добавить" />
        </td>
    </tr>
   
</table>
}

EmployeeTable/EmployeeTable/Views/Home/Delemp.cshtml
@model EmployeeTable.Models.Employee

@{
    Layout = "~/Views/Layout/_Layout.cshtml";
}

@*Страница удаления существующего сотрудника

    LabelFor - отображение обозначения (названия) поля для воода
    DisplayFor - отображение значения поля
*@

<h3>Удаление сотрудника</h3>
@using (Html.BeginForm())
{

    <table>
        <tr class="header"> @*Строка с заголовками таблицы*@
            <td width="10%">
                @Html.LabelFor(model => model.IdEmployee, "Номер записи")
            </td>
            <td>
                @Html.LabelFor(model => model.Fullname, "Фамилия и инициалы")

            </td>
            <td>
                @Html.LabelFor(model => model.Position.Name, "Должность")
            </td>
        </tr>
        <tr>@*Строка с данными*@
            <td>
                @Html.DisplayFor(model => model.IdEmployee)
            </td>
            <td>
                @Html.DisplayFor(model => model.Fullname)
            </td>
            <td>
                @Html.DisplayFor(model => model.Position.Name)
            </td>
        </tr>
        <tr>
            <td colspan="3">
                <input type="submit" value="Удалить" class="button15" />
            </td>
        </tr>
    </table>

}

EmployeeTable/EmployeeTable/Views/Home/Delete.cshtml
@model EmployeeTable.Models.Absence
@{
    Layout = "~/Views/Layout/_Layout.cshtml";
}

@*Cтраница с вопросом о подрверджении удаления записи об отсутствии*@
<h3>Удаление записи об отсутствии</h3>

@using (Html.BeginForm())
{
    <table>
        <tr>
            <td>
                Вы действительно хотите удалить запись?
            </td>
        </tr>
        <tr>
            <td>

                <input type="submit" value="Удалить" class="button15" />

            </td>
        </tr>
    </table>
}

EmployeeTable/EmployeeTable/Views/Home/Employees.cshtml
@model IEnumerable<EmployeeTable.Models.Employee>
@{
    Layout = "~/Views/Layout/_Layout.cshtml";
}

@*Страница отображающая всех сотрудников

    ActionLink - переход по ссылке на страницу
    DisplayFor - отображение значения поля
    HiddenFor - скрытое отображения поля
*@


<h3>Сотрудники</h3>

<table>
    @*Строка с заголовками таблицы*@
    <tr class="header">

        <td>Фамилия</td>
        <td>Имя</td>
        <td>Отчество</td>
        <td>Полное имя</td>
        <td>Должность</td>
        <td colspan="2"></td>
    </tr>
    @*Цикл, выбирающий сотрудников из модели*@
    @foreach (var item in Model)
    {
    <tr>
        @*Уникальный номер*@
        @Html.HiddenFor(model => item.IdEmployee)
        <td>
            @Html.DisplayFor(model => item.Surname)
        </td>


        <td>
            @Html.DisplayFor(model => item.Name)
        </td>

        <td>
            @Html.DisplayFor(model => item.Lastname)
        </td>

        <td>
            @Html.DisplayFor(model => item.Fullname)
        </td>

        <td>
            @Html.DisplayFor(model => item.Position.Name)
        </td>
        <td>
            @*Кнопка удаления*@
            @Html.ActionLink("X", "Delemp", new { id = item.IdEmployee }, new { @class = "DeleteEntry" })
        </td>
        <td>
            @*Кнопка редактирования*@
            @Html.ActionLink("M", "ModifyEmp", new { id = item.IdEmployee }, new { @class = "ModifyEntry" })
        </td>
    </tr>
    }
</table>

EmployeeTable/EmployeeTable/Views/Home/Index.cshtml
@model EmployeeTable.Models.AbsenceListViewModel

@{
    Layout = "~/Views/Layout/_Layout.cshtml";
}

@*
            "Главная страница". Содежит основной список сотрудников и дат их отсутствий. А так же причины

             DisplayFor - отображение значения поля
             ActionLink - переход по ссылке на страницу
             DropDownList - выпадающий список
    **@


<body>

    <h3>Список отсутствий</h3>

    <form method="get">
        <div class="form-inline">
            <table>
                <tr class="header">
                    @* Строка с фильтрами *@
                    <td>
                        <p>Фильтр</p>
                    </td>
                    <td>
                        <label class="control-label">ФИО: </label>
                        @Html.DropDownList("Fullname", Model.Fullnames as SelectList,
                                    htmlAttributes: new { @class = "form-control" })
                    </td>
                    <td>
                        <label class="control-label">Должность: </label>
                        @Html.DropDownList("Name", Model.Names as SelectList,
                                    htmlAttributes: new { @class = "form-control" })
                    </td>
                    <td>
                        <label class="control-label">Причина: </label>
                        @Html.DropDownList("Reason", Model.Reason as SelectList,
                                    htmlAttributes: new { @class = "form-control" })
                    </td>
                    <td>
                        <input type="submit" value="Применить" class="button15" />
                    </td>
                </tr>
            </table>
        </div>
    </form>

    <div>
        <table>
            @* Основная таблица *@
            @* Заголовок *@
            <tr class="header">
                <td>
                    ФИО
                </td>
                <td>
                    <p> Должность </p>
                </td>
                <td>
                    <p> Дата отсутствия</p>
                </td>
                <td>
                    <p> Причина отсутствия </p>
                </td>
                <td colspan="2"></td>
            </tr>
            @* Цикл выводящий строки из таблицы БД *@
            @foreach (var item in Model.Absences)
            {
                <tr>
                    <td>
                        @* ФИО *@
                        @Html.DisplayFor(modelitem => item.Employee.Fullname)
                    </td>
                    <td>
                        @* Должность *@
                        @*@Html.DisplayFor(modelitem => item.Employee.Position)*@
                        @Html.DisplayFor(modelitem => item.Employee.Position.Name)
                    </td>
                    <td>
                        @* Дата отсутствия *@
                        @Html.DisplayFor(modelitem => item.Date, "{0:dd.MM.yyyy hh:mm}", new { @class = "form-control default-date-picker" })
                    </td>
                    <td>
                        @*Причина отсутствия*@
                        @Html.DisplayFor(modelitem => item.Reason)
                    </td>
                    <td>
                        @*Кнопка удаления*@
                        @Html.ActionLink("X", "Delete", new { id = item.IdAbsences }, new { @class = "DeleteEntry" })
                    </td>
                    <td>
                        @Html.ActionLink("M", "Modify", new { id = item.IdAbsences }, new { @class = "ModifyEntry" })
                    </td>
                </tr>
            }
        </table>

    </div>


</body>

EmployeeTable/EmployeeTable/Views/Home/Modify.cshtml
@model EmployeeTable.Models.Absence

@{
    Layout = "~/Views/Layout/_Layout.cshtml";
}

@*Страница изменения данных об отсутвии

    ActionLink - переход по ссылке на страницу
    LabelFor - отображение названия для вводимого поля
    HiddenFor - скрытое отображения поля
    DropDownListFor - выпадающий список
    ValidationMessageFor - проверка корректности ввода со стороны пользователя (отображает ошибку)
*@

<h3>Редактирование записи @Model.Date </h3>
@using (Html.BeginForm("Modify", "Home", FormMethod.Post))
{
    <table>
        <tr>
            <td width="20%">
                @*Уникальный номер записи об отсутствии*@
                @Html.HiddenFor(m => m.IdAbsences)
                @*Фамилия и инициалы*@
                @Html.LabelFor(m => m.Employee.Fullname, "ФИО")
            </td>
                @*Выпадающий список с инициалами сотрудников*@
            <td width="40%" align="left">
                @Html.DropDownListFor(model => model.idEmployee, ViewBag.Employees as SelectList)
            </td>
            <td width="40%"></td>
        </tr>
        <tr>
            <td>
                @*Дата отсутствия*@
            @Html.LabelFor(m => m.Reason, "Дата")
        </td>
            @*Отображение календаря для ввода даты*@
        <td align="left">
            @Html.EditorFor(model => model.Date, new { @class = "form-control default-date-picker" })
        </td>
        <td>
            @*Проверка вводимого значения*@
            @Html.ValidationMessageFor(modek => Model.Date)
        </td>
        </tr>
        <tr>
            <td>
                @*Причина отсутвия*@
                @Html.LabelFor(m => m.Reason, "Причина")
            </td>
            <td align="left">
                @*Вводится текст причины отсутствия*@
                @Html.EditorFor(m => m.Reason)
            </td>
            <td>
                @*Проверка значения*@
                @Html.ValidationMessageFor(m => m.Reason)
            </td>
        </tr>
        <tr>
            <td colspan="3">
                @*Кнопка подтверждения*@
                    <input type="submit" value="Отправить" class="button15"/>
            </td>
        </tr>
    </table>
}

EmployeeTable/EmployeeTable/Views/Home/ModifyEmp.cshtml
@model EmployeeTable.Models.Employee
@{
    Layout = "~/Views/Layout/_Layout.cshtml";
}

@*Страница изменения данных об отсутвии

    LabelFor - отображение названия для вводимого поля
    ValidationMessageFor - проверка корректности ввода со стороны пользователя (отображает ошибку)
    EditorFor - поле для ввода текста
*@


<h3>Редактирование записи @Model.Fullname</h3>

@*Отправляем РОST запрос серверу в контроллер*@
@using (Html.BeginForm("ModifyEmp", "Home", FormMethod.Post))
{
<table>
    <tr>
        <td width="20%">
            @*Таблица содержащая фамилию, имя, отчество и должность сотрудника
            Поле фамилия и инициалы заполняется автоматически в контроллере
            *@
            @Html.HiddenFor(m => m.IdEmployee)

            @Html.LabelFor(m => m.Surname, "Фамилия")
        </td>
        <td width="40%">
            @Html.EditorFor(m => m.Surname)
        </td>
        <td width="40%">
            @Html.ValidationMessageFor(model => model.Surname)
        </td>
    </tr>
    <tr>
        <td>
            @Html.LabelFor(m => m.Name, "Имя")
        </td>
        <td>
            @Html.EditorFor(m => m.Name)
        </td>
        <td>
            @Html.ValidationMessageFor(model => model.Name)
        </td>
    </tr>
    <tr>
        <td>
            @Html.LabelFor(model => model.Lastname, "Отчество")
        </td>
        <td>
            @Html.EditorFor(model => model.Lastname)
        </td>
        <td>
            @Html.ValidationMessageFor(model => model.Lastname)
        </td>
    </tr>
    <tr>
        <td>
            @Html.LabelFor(model => model.Position.Name, "Должность")
        </td>
        <td>
            @Html.HiddenFor(model => model.idPosition)
            @Html.HiddenFor(model=>model.Position.IdPosition)
            @Html.EditorFor(model => model.Position.Name)
        </td>
        <td>
            @Html.ValidationMessageFor(model => model.Position.Name)
        </td>
    </tr>
<tr>
    <td colspan="3">
        <input type="submit" value="Отправить" class="button15"/>
    </td>
</tr>
</table>
}

EmployeeTable/EmployeeTable/Views/Home/Newemp.cshtml
@model EmployeeTable.Models.Employee

@{
    Layout = "~/Views/Layout/_Layout.cshtml";
}

@*Страница изменения данных об отсутвии

    LabelFor - отображение названия для вводимого поля
    ValidationMessageFor - проверка корректности ввода со стороны пользователя (отображает ошибку)
    EditorFor - поле для ввода текста
*@

<h3>Добавление сотрудника</h3>

@using (Html.BeginForm())
{
<table>
    <tr>
        <td width="20%">
            @Html.LabelFor(model => model.Surname, "Фамилия")
        </td>
        <td width="20%" align="left">
            @Html.EditorFor(model => model.Surname)
            @Html.Hidden("Fullname"," ")
        </td>
        <td width="60%">
            @Html.ValidationMessageFor(model => model.Surname)
        </td>

    </tr>
    <tr>
        <td>
            @Html.LabelFor(model => model.Name, "Имя")
        </td>
        <td align="left">
            @Html.EditorFor(model => model.Name)
        </td>
        <td>
            @Html.ValidationMessageFor(model => model.Name)
        </td>
    </tr>
    <tr>
        <td>
            @Html.LabelFor(model => model.Lastname, "Отчество")
        </td>
        <td align="left">
            @Html.EditorFor(model => model.Lastname)
        </td>
        <td>
            @Html.ValidationMessageFor(model => Model.Lastname)
        </td>
    </tr>
    <tr>
        <td>
            @Html.LabelFor(model => model.Position.Name, "Должность")
        </td>
        <td align="left">
            @Html.EditorFor(model => model.Position.Name)
        </td>
        <td>
            @Html.ValidationMessageFor(model => Model.Position.Name)
        </td>
    </tr>
    
    <tr>

        <td colspan="3">
            <input type="submit" value="Добавить" class="button15" />
        </td>
    </tr>

</table>
}